### ISSUE TITLE
[Bug]: Refined Storage fluid storage auto crafting system causes world to crash

### ISSUE THREAD

**Issue by MACSkeptic** [DarkPacks/SkyFactory-One#149]
### General Info

- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player (did not try, wouldn't assume it makes any difference in this case)
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Modpack version

1.0.3

### Java version

1.8.0_51

### Modpack Launcher Used

CurseForge Launcher

### Memory Allocated

16 GB (my system has 32 GB)

### Minecraft World Environment

Single Player

### Misc Client Info

- [ ] Optifine Installed
- [ ] Shaders Installed

### Misc Server Info

- [ ] Sponge or Non-Vanilla Forge Server

### Issue Description

As soon as I created a Tesseract, minecraft crashed and I cannot even load my world anymore (crashes instantaneously)

More detailed description

- Generally small world, early mid game, just starting with Refined Storage autocrafting.
- Setting up recipees for ender chests and ender tanks on autocrafting (never crafted one in this world)
- Setting up recipee for tesseract on autocrafting (never crafted one in this world)
- Requested a tesseract via auto crafting, it says I'd need an ender chest (even though I just added in a recipee for that)
- I imagined it was something silly like the recipee being bound to an ender chest with colors or something like that, decided to just request an ender chest
- Game crashed (I'd assume as soon as the ender chest got created) and I could never open the world again

##### Minor update

I tried re-creating this exact same setup in a minimalistic creative world and failed (i.e.: no crash)...

In my creative world I had:

- Refined Storage
- Autocrafting for tesseract/ender chest
- Tried requesting a tesseract (it didn't work, I'm pretty sure there is a bug here)
- Tried ctrl clicking it from JEI on a crafting terminal, it populated everything but not the ender chest
- Requested an ender chest (from Refined Storage auto crafting) and manually put it in the grid. Could create and place a tesseract with no problems.
- There was a basic chunk loader in place, similar to my own world that seems to have gotten corrupt

Guesses:

- ~~~Something else that happens on tick is interfering with it~~~
- ~~~Could be wireless transfer nodes from cyclic?~~~
- It seems to be related to refined storage crafting queue, particularly around liquids, likely running into this specific exception: https://github.com/refinedmods/refinedstorage/blob/9c21cad9f62fdfe022d3a6049ce3f9b9a112c505/src/main/java/com/refinedmods/refinedstorage/apiimpl/autocrafting/task/v6/node/NodeRequirements.java#L140

From Logs:

```
[17:05:20] [Server thread/ERROR]: Exception caught during firing event: Bad!
	Index: 8
	Listeners:
		0: HIGH
		1: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$2948/1446527985@b4478e8
		4: ASM: class com.supermartijn642.chunkloaders.ChunkLoaderUtil onTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		5: ASM: class com.supermartijn642.tesseract.manager.TesseractTracker onTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		6: net.minecraftforge.eventbus.EventBus$$Lambda$2948/1446527985@7206fd86
		7: ASM: class cofh.thermal.cultivation.event.TCulCommonEvents handleTickEndEvent(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		8: ASM: com.refinedmods.refinedstorage.apiimpl.network.NetworkListener@2f7e30e2 onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		9: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@797b51da worldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		10: ASM: com.bloodnbonesgaming.topography.client.events.ClientEventHandler@3beec249 OnWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		11: net.minecraftforge.eventbus.EventBus$$Lambda$2948/1446527985@2d7dd3fc
		12: ASM: mcjty.rftoolsbuilder.modules.scanner.ShapeHandler@7b1f6617 onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		13: ASM: com.natamus.collective.events.CollectiveEvents@49b62cc7 onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		14: LOWEST
		15: ASM: com.bloodnbonesgaming.topography.client.events.ClientEventHandler@3beec249 onAllEvents(Lnet/minecraftforge/eventbus/api/Event;)V
java.lang.IllegalStateException: Bad!
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.node.NodeRequirements.getSingleFluidRequirementSet(NodeRequirements.java:140)
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.node.ProcessingNode.update(ProcessingNode.java:123)
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.CraftingTask.update(CraftingTask.java:191)
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.updateTasks(CraftingManager.java:170)
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:134)
	at com.refinedmods.refinedstorage.apiimpl.network.Network.update(Network.java:165)
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onWorldTick(NetworkListener.java:17)
	at net.minecraftforge.eventbus.ASMEventHandler_873_NetworkListener_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$3674/493359309.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:100)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:857)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$16846/2085099859.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

[17:05:20] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Bad!
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.node.NodeRequirements.getSingleFluidRequirementSet(NodeRequirements.java:140) ~[?:1.9.16]
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.node.ProcessingNode.update(ProcessingNode.java:123) ~[?:1.9.16]
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.CraftingTask.update(CraftingTask.java:191) ~[?:1.9.16]
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.updateTasks(CraftingManager.java:170) ~[?:1.9.16]
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:134) ~[?:1.9.16]
	at com.refinedmods.refinedstorage.apiimpl.network.Network.update(Network.java:165) ~[?:1.9.16]
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onWorldTick(NetworkListener.java:17) ~[?:1.9.16]
	at net.minecraftforge.eventbus.ASMEventHandler_873_NetworkListener_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3674/493359309.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:100) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:857) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$16846/2085099859.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[17:05:20] [Server thread/FATAL]: Preparing crash report with UUID a537c7f6-168f-44f0-99d6-71f63c80089d
```

### Additional Information

https://pastebin.com/gWVjMdbS

**Comment by MACSkeptic** [comment]
any ideas on how I could at least uncorrupt my world?

**Comment by MACSkeptic** [comment]
new Update:

I've downloaded https://github.com/jaquadro/NBTExplorer/releases/tag/v2.8.0-win and managed to switch my refined storage to off (by changing mode from 2 to 1 via save edit) and now I can at least load into it!

**Comment by MACSkeptic** [comment]
@Darkosto feel free to close and ignore this, I'm thinking this is strictly a refined storage problem, not a sky factory problem

**Comment by Darkosto** [comment]
Glad you got it figured out!
